#pragma once

#define XPVIEW_VERSION_MAJOR 1
#define XPVIEW_VERSION_MINOR 1
#define XPVIEW_VERSION_PATCH 0
#define XPVIEW_VERSION_BUILD 0

#define XPVIEW_FILE_VERSION XPVIEW_VERSION_MAJOR,XPVIEW_VERSION_MINOR,XPVIEW_VERSION_PATCH,XPVIEW_VERSION_BUILD
#define XPVIEW_VERSION_STRING_A "1.1.0"
#define XPVIEW_VERSION_STRING_W L"1.1.0"

#define XPVIEW_PRODUCT_NAME_A "XPview - Imperivm III Hero Overlay"
#define XPVIEW_PRODUCT_NAME_W L"XPview - Imperivm III Hero Overlay"
#define XPVIEW_CONTROLLER_TITLE_W L"XPview 1.1.0 - Imperivm Overlay Controller"
#define XPVIEW_OVERLAY_TITLE_W L"XPview 1.1.0 - Hero Overlay"
